name: Deploy Terraform AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: cd terraform && terraform init

      - name: Terraform Plan
        run: cd terraform && terraform plan -var="bucket_name=biki-devops-bucket"

      - name: Terraform Apply
        run: cd terraform && terraform apply -auto-approve -var="bucket_name=biki-devops-bucket-2025"

